type: pipeline_definition
product: Liberty
name: Open Liberty Delivery Requirements Verification
description: "Examines Open Liberty code changes for delivery standards compliance"
triggers:
- type: github
  description: "Runs CI Orchestrator-managed Jenkins jobs to examine pull request changes and create required status checks"
  triggerName: "libby"
  triggerRank: 50
  groups: ["LibertyDev"]
  keyword: "!libby"
  aliasKeywords:
    - "#run-libby-bot"
    - "#run-libby"
    - "#libby"
  propertyDefinitions:
    - name: githubPRNumber
      defaultValue: ${github_pr_number}
    - name: githubPRApi
      defaultValue: ${github_pr_api}

steps:
- stepName: PR Changes
  workType: PRChangesDetection
  timeoutInMinutes: 30
- stepName: Copyright Header Check
  workType: Jenkins
  projectName: copyrightHeaderCheck
  timeoutInMinutes: 120
- stepName: Prohibited Terms Check
  workType: Jenkins
  projectName: prohibitedTermsCheck
  timeoutInMinutes: 120
- stepName: Code Checklist Creation
  workType: Jenkins
  projectName: codeCheckListBuilder
  timeoutInMinutes: 120
  dependsOn:
  - stepName: PR Changes
    awaitOutputProperties: true
  properties:
    isProductCodeChanged: ${PR Changes:is.product.code.changed}
    isFatCodeChanged: ${PR Changes:is.fat.code.changed}
    isUnittestCodeChanged: ${PR Changes:is.unittest.code.changed}    
    isBvtCodeChanged: ${PR Changes:is.bvt.code.changed}
    isTestInfraCodeChanged: ${PR Changes:is.test.infra.code.changed}
    isInfraCodeChanged: ${PR Changes:is.infra.code.changed}
