receivers:
 otlp:
   protocols:
     grpc:

exporters:
 prometheus:
  endpoint: otel-collector-metrics:3131


processors:
 batch:
   timeout: 0s

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
<<<<<<< HEAD
      exporters: [prometheus]
=======
      exporters: [logging]
>>>>>>> 520a56a139 (TelemetryAloneTest requires Java 11)
